-- ----------------------------
-- Table structure for db_operator
-- ----------------------------
CREATE TABLE "DB_OPERATOR" (
    "STATEMENT" VARCHAR2(64) NOT NULL ENABLE, 
    "OPT_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
    "OPT_STATEMENT_TYPE" VARCHAR2(32) NOT NULL ENABLE, 
    "OPT_TARGET" VARCHAR2(32), 
    "OPT_VALUE" VARCHAR2(1024) NOT NULL ENABLE, 
    "OPT_PK" VARCHAR2(32), 
    "OPT_RULES" VARCHAR2(512), 
    "BEFORE_OPT" VARCHAR2(32), 
    "AFTER_OPT" VARCHAR2(32), 
    "OPT_DESC" VARCHAR2(256),
     CONSTRAINT "DB_OPERATOR" PRIMARY KEY ("STATEMENT")
   );;
   
   ALTER TABLE DB_OPERATOR ADD OPT_VALUE_TYPE VARCHAR2(1) DEFAULT '0';;
   ALTER TABLE DB_OPERATOR ADD OPT_RULES VARCHAR2(1024) DEFAULT NULL;;
   
   COMMENT ON TABLE "DB_OPERATOR"  IS '操作表';;
   COMMENT ON COLUMN "DB_OPERATOR"."STATEMENT" IS '操作别名';;
   COMMENT ON COLUMN "DB_OPERATOR"."OPT_TYPE" IS '操作数据库类型  RMDB MONGO';;
   COMMENT ON COLUMN "DB_OPERATOR"."OPT_STATEMENT_TYPE" IS '操作方式类型';;
   COMMENT ON COLUMN "DB_OPERATOR"."OPT_TARGET" IS '操作对象';;
   COMMENT ON COLUMN "DB_OPERATOR"."OPT_VALUE" IS '操作语句';;
   COMMENT ON COLUMN "DB_OPERATOR"."OPT_RULES" IS '校验规则';;
   COMMENT ON COLUMN "DB_OPERATOR"."OPT_VALUE_TYPE" IS '操作语句类型 0:SQL 1:存储过程';;
-- ----------------------------
-- Table structure for db_sequence
-- ----------------------------
CREATE TABLE "DB_SEQUENCE" (
    "SEQ_NAME" VARCHAR2(64) NOT NULL ENABLE, 
    "TAB_NAME" VARCHAR2(64), 
    "INIT_VALUE" NUMBER(11), 
    "INCREASE_VALUE" NUMBER(11), 
    "SEQUENCE_ID" NUMBER(11), 
    "LAST_ID" VARCHAR2(64), 
    "LAST_TIME" DATE, 
    CONSTRAINT "DB_SEQUENCE_PK" PRIMARY KEY ("SEQ_NAME")
);;

   COMMENT ON COLUMN "DB_SEQUENCE"."SEQ_NAME" IS '序列名';;
   COMMENT ON COLUMN "DB_SEQUENCE"."TAB_NAME" IS '表名';;
   COMMENT ON COLUMN "DB_SEQUENCE"."INIT_VALUE" IS '初始值';;
   COMMENT ON COLUMN "DB_SEQUENCE"."INCREASE_VALUE" IS '增加值';;
   COMMENT ON COLUMN "DB_SEQUENCE"."SEQUENCE_ID" IS '当前值';;
   COMMENT ON COLUMN "DB_SEQUENCE"."LAST_ID" IS '修改人';;
   COMMENT ON COLUMN "DB_SEQUENCE"."LAST_TIME" IS '修改时间';;
   COMMENT ON TABLE "DB_SEQUENCE"  IS '序列表';;

CREATE PROCEDURE SEQ_NEXT_VAL(seqName IN VARCHAR2,seqId OUT number) AS
BEGIN
  select (sequence_id+increase_value) into seqId from db_sequence where seq_name=seqName;
  UPDATE db_sequence SET sequence_id=seqId, last_time=sysdate WHERE 1=1 and seq_name=seqName;
END;
;;